### ISSUE TITLE
User can create a new account

### ISSUE THREAD

**Issue by lhansra** [codepath-covid-app/codepath-app#1]

**Comment by Daphne-CPAdmin** [comment]
Missed the following required user stories for Unit 9:

- GitHub Project created (1pt)
- GitHub Milestones created (1pt)
- Issues added to project and assigned to specific team members (1pt)

**Comment by lhansra** [comment]
Hello,

I forgot to make the project public but we did create it and the milestones. I just updated it to be public. 

Lovpreet Hansra

**Comment by Daphne-CPAdmin** [comment]
Missing:

Gifs created to show build progress and added to README (3pts)
